// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ieqpfhmuvhuzjezwtohs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcXBmaG11dmh1emplend0b2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTYwMTEsImV4cCI6MjA3MjI3MjAxMX0.-3DRu4XZeYi5hmk_hPQkwFA-9rg9ngNcLDbSoHUttyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);